spring.application.name=blog-backend

cloudinary.cloud-name

cloudinary.api-key

cloudinary.api-secret

jwt-secret

spring.mongodb.uri

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://<host>:<port>/<database>
spring.datasource.username=<username>
spring.datasource.password=<password>
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

